version: '3.4'

services:
  prudcutmicroserve:
    image: ${DOCKER_REGISTRY-}prudcutmicroserve
    build:
      context: .
      dockerfile: PrudcutMicroserve/Dockerfile
    environment:
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=192.168.100.18,1433;Initial Catalog=ProductServiceDB;User Id=sa;Password=SA@12saf;Trusted_Connection=False; MultipleActiveResultSets=true;
    ports:
    - "3000:80"